name: Validate on MR
on:
  workflow_displatch:
  pull_request:
    branches:
      [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '11'
        - uses: subosito/flutter-action@v2.7.1
          with:
            flutter-version: '2.5.3'
            cache: true
        - run: flutter pub get
        - run: flutter analyze
